# Generated by Django 5.1.8 on 2025-11-19 08:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("invoices", "0016_contract_position_cost_type_to_publish"),
        ("publications", "0044_alter_publicationpayment_publication"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenCostReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("period_start", models.DateField(help_text="Start of reporting period")),
                ("period_end", models.DateField(help_text="End of reporting period")),
                (
                    "generated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this report was generated",
                    ),
                ),
                ("xml_content", models.TextField(blank=True, help_text="Generated OpenCost XML")),
            ],
            options={
                "verbose_name": "OpenCost Report",
                "verbose_name_plural": "OpenCost Reports",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="OpenCostReportInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True, help_text="Invoice number (snapshot)", max_length=255
                    ),
                ),
                (
                    "creditor",
                    models.CharField(
                        blank=True, help_text="Creditor/publisher name (snapshot)", max_length=255
                    ),
                ),
                (
                    "invoice_date",
                    models.DateField(blank=True, help_text="Invoice date (snapshot)", null=True),
                ),
                (
                    "snapshot_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this snapshot was created",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        help_text="Original CODA invoice (for navigation links)",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="invoices.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Invoice",
                "verbose_name_plural": "Report Invoices",
                "ordering": ["invoice_number"],
            },
        ),
        migrations.CreateModel(
            name="OpenCostReportInvoicePosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4, help_text="Cost amount (snapshot)", max_digits=20
                    ),
                ),
                ("currency", models.CharField(help_text="Currency code (snapshot)", max_length=3)),
                (
                    "cost_type",
                    models.CharField(help_text="OpenCost cost type (snapshot)", max_length=50),
                ),
                (
                    "vat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="VAT/tax rate (snapshot)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "snapshot_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this snapshot was created",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        help_text="Original CODA position",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="invoices.position",
                    ),
                ),
                (
                    "report_invoice",
                    models.ForeignKey(
                        help_text="The report invoice this position belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="opencost.opencostreportinvoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Invoice Position",
                "verbose_name_plural": "Report Invoice Positions",
                "ordering": ["amount"],
            },
        ),
        migrations.CreateModel(
            name="OpenCostReportPublication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Publication title (snapshot)", max_length=500),
                ),
                ("doi", models.CharField(blank=True, help_text="DOI (snapshot)", max_length=255)),
                (
                    "publication_type",
                    models.CharField(help_text="COAR publication type (snapshot)", max_length=100),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True, help_text="Publisher name (snapshot)", max_length=500
                    ),
                ),
                (
                    "journal",
                    models.CharField(
                        blank=True, help_text="Journal name (snapshot)", max_length=500
                    ),
                ),
                (
                    "external_costsplitting",
                    models.BooleanField(
                        blank=True,
                        help_text="Whether publication has multi-institutional cost sharing",
                        null=True,
                    ),
                ),
                (
                    "snapshot_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this snapshot was created",
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        help_text="Original CODA publication (for navigation links)",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="publications.publication",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        help_text="The report this publication belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publications",
                        to="opencost.opencostreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Publication",
                "verbose_name_plural": "Report Publications",
                "ordering": ["title"],
                "unique_together": {("report", "publication")},
            },
        ),
        migrations.AddField(
            model_name="opencostreportinvoice",
            name="report_publication",
            field=models.ForeignKey(
                help_text="The report publication this invoice belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="opencost.opencostreportpublication",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="opencostreportinvoice",
            unique_together={("report_publication", "invoice")},
        ),
    ]
