# Generated by Django 5.1.8 on 2025-11-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opencost", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opencostreportinvoiceposition",
            name="vat",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="VAT/tax amount (snapshot)",
                max_digits=10,
                null=True,
            ),
        ),
    ]
