# Generated by Django 5.1.8 on 2025-11-21 16:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opencost", "0002_alter_opencostreportinvoiceposition_vat"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenCostReportPublicationLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        help_text="Link type (e.g., 'handle', 'urn') (snapshot)", max_length=50
                    ),
                ),
                (
                    "value",
                    models.CharField(help_text="Link value/identifier (snapshot)", max_length=500),
                ),
                (
                    "snapshot_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this snapshot was created",
                    ),
                ),
                (
                    "report_publication",
                    models.ForeignKey(
                        help_text="The report publication this link belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="opencost.opencostreportpublication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Publication Link",
                "verbose_name_plural": "Report Publication Links",
                "ordering": ["link_type", "value"],
            },
        ),
    ]
