# Generated by Django 5.1.8 on 2025-11-25 15:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opencost", "0003_opencostreportpublicationlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="opencostreportpublication",
            name="institution_name",
            field=models.CharField(
                blank=True, help_text="Institution name (snapshot)", max_length=500
            ),
        ),
        migrations.CreateModel(
            name="OpenCostReportInstitutionIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "identifier_type",
                    models.CharField(
                        help_text="Type of identifier: ror, isni, or ringold (snapshot)",
                        max_length=50,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Institution identifier value (snapshot)", max_length=500
                    ),
                ),
                (
                    "snapshot_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this snapshot was created",
                    ),
                ),
                (
                    "report_publication",
                    models.ForeignKey(
                        help_text="The report publication this institution identifier belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institution_identifiers",
                        to="opencost.opencostreportpublication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Institution Identifier",
                "verbose_name_plural": "Report Institution Identifiers",
                "ordering": ["identifier_type", "value"],
            },
        ),
    ]
