# Generated by Django 5.1.8 on 2025-11-28 09:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_contract_publication_billing"),
        ("invoices", "0016_contract_position_cost_type_to_publish"),
        ("opencost", "0004_opencostreportpublication_institution_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenCostReportContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "contract_name",
                    models.CharField(help_text="Contract name (snapshot)", max_length=255),
                ),
                (
                    "institution_name",
                    models.CharField(
                        blank=True, help_text="Institution name (snapshot)", max_length=500
                    ),
                ),
                (
                    "participation_from",
                    models.DateField(
                        blank=True,
                        help_text="Contract participation start date (snapshot)",
                        null=True,
                    ),
                ),
                (
                    "participation_to",
                    models.DateField(
                        blank=True,
                        help_text="Contract participation end date (snapshot)",
                        null=True,
                    ),
                ),
                (
                    "primary_identifier_value",
                    models.CharField(
                        blank=True,
                        help_text="Primary identifier value (ESAC ID) (snapshot)",
                        max_length=500,
                    ),
                ),
                (
                    "snapshot_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this snapshot was created",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        help_text="Original CODA contract (for navigation links)",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contracts.contract",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        help_text="The report this contract belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="opencost.opencostreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Contract",
                "verbose_name_plural": "Report Contracts",
                "ordering": ["contract_name"],
                "unique_together": {("report", "contract")},
            },
        ),
        migrations.CreateModel(
            name="OpenCostReportContractInstitutionIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "identifier_type",
                    models.CharField(
                        help_text="Type of identifier: ror, isni, or ringold (snapshot)",
                        max_length=50,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Institution identifier value (snapshot)", max_length=500
                    ),
                ),
                (
                    "snapshot_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this snapshot was created",
                    ),
                ),
                (
                    "report_contract",
                    models.ForeignKey(
                        help_text="The report contract this institution identifier belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institution_identifiers",
                        to="opencost.opencostreportcontract",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Contract Institution Identifier",
                "verbose_name_plural": "Report Contract Institution Identifiers",
                "ordering": ["identifier_type", "value"],
            },
        ),
        migrations.CreateModel(
            name="OpenCostReportContractInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True, help_text="Invoice number (snapshot)", max_length=255
                    ),
                ),
                (
                    "creditor",
                    models.CharField(
                        blank=True, help_text="Creditor/publisher name (snapshot)", max_length=255
                    ),
                ),
                (
                    "invoice_date",
                    models.DateField(blank=True, help_text="Invoice date (snapshot)", null=True),
                ),
                (
                    "amount_invoice",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Total invoice amount (snapshot)",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "amount_invoice_currency",
                    models.CharField(
                        blank=True, help_text="Invoice amount currency (snapshot)", max_length=3
                    ),
                ),
                (
                    "snapshot_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this snapshot was created",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        help_text="Original CODA invoice (for navigation links)",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="invoices.invoice",
                    ),
                ),
                (
                    "report_contract",
                    models.ForeignKey(
                        help_text="The report contract this invoice belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="opencost.opencostreportcontract",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Contract Invoice",
                "verbose_name_plural": "Report Contract Invoices",
                "ordering": ["invoice_number"],
                "unique_together": {("report_contract", "invoice")},
            },
        ),
        migrations.CreateModel(
            name="OpenCostReportContractInvoicePosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4, help_text="Cost amount (snapshot)", max_digits=20
                    ),
                ),
                ("currency", models.CharField(help_text="Currency code (snapshot)", max_length=3)),
                (
                    "cost_type",
                    models.CharField(
                        help_text="OpenCost contract cost type (publish/read/vat) (snapshot)",
                        max_length=50,
                    ),
                ),
                (
                    "vat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="VAT/tax amount (snapshot)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "snapshot_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this snapshot was created",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        help_text="Original CODA position",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="invoices.position",
                    ),
                ),
                (
                    "report_contract_invoice",
                    models.ForeignKey(
                        help_text="The report contract invoice this position belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="opencost.opencostreportcontractinvoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Contract Invoice Position",
                "verbose_name_plural": "Report Contract Invoice Positions",
                "ordering": ["amount"],
            },
        ),
        migrations.CreateModel(
            name="OpenCostReportContractSecondaryIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "identifier_type",
                    models.CharField(
                        help_text="Type of identifier: oai, ezb, or local (snapshot)", max_length=50
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Secondary identifier value (snapshot)", max_length=500
                    ),
                ),
                (
                    "snapshot_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this snapshot was created",
                    ),
                ),
                (
                    "report_contract",
                    models.ForeignKey(
                        help_text="The report contract this secondary identifier belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secondary_identifiers",
                        to="opencost.opencostreportcontract",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Contract Secondary Identifier",
                "verbose_name_plural": "Report Contract Secondary Identifiers",
                "ordering": ["identifier_type", "value"],
            },
        ),
    ]
