# Generated by Django 5.1.8 on 2025-12-04 14:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0004_add_contract_links"),
        ("opencost", "0005_opencostreportcontract_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenCostReportPublicationContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "contract_year",
                    models.IntegerField(
                        help_text="Year of contract participation (snapshot from AttachedContract)"
                    ),
                ),
                (
                    "group_id",
                    models.CharField(
                        blank=True,
                        help_text="Optional group ID for OpenCost part_of_contract",
                        max_length=255,
                    ),
                ),
                (
                    "snapshot_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this snapshot was created",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        help_text="Contract this publication is part of",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contracts.contract",
                    ),
                ),
                (
                    "report_publication",
                    models.ForeignKey(
                        help_text="The report publication this contract link belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_contracts",
                        to="opencost.opencostreportpublication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Publication Contract",
                "verbose_name_plural": "Report Publication Contracts",
                "ordering": ["contract_year"],
                "unique_together": {("report_publication", "contract")},
            },
        ),
    ]
