# Generated by Django 5.1.8 on 2025-12-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opencost", "0006_add_publication_contract_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="opencostreportcontractinvoice",
            name="group_id",
            field=models.CharField(
                blank=True,
                help_text="UUID4 to group invoices and link to publications (for part_of_contract)",
                max_length=255,
            ),
        ),
    ]
