# Generated by Django 5.1.8 on 2025-12-16 14:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opencost", "0007_add_group_id_to_contract_invoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opencostreportcontract",
            name="snapshot_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="opencostreportcontractinstitutionidentifier",
            name="snapshot_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="opencostreportcontractinvoice",
            name="snapshot_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="opencostreportcontractinvoiceposition",
            name="snapshot_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="opencostreportcontractsecondaryidentifier",
            name="snapshot_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="opencostreportinstitutionidentifier",
            name="snapshot_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="opencostreportinvoice",
            name="snapshot_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="opencostreportinvoiceposition",
            name="snapshot_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="opencostreportpublication",
            name="snapshot_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="opencostreportpublicationcontract",
            name="snapshot_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="opencostreportpublicationlink",
            name="snapshot_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
