# Generated by Django 5.1.8 on 2025-12-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opencost", "0008_alter_opencostreportcontract_snapshot_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opencostreport",
            name="errors_count",
            field=models.IntegerField(
                default=0, help_text="Number of validation errors in this report"
            ),
        ),
        migrations.AddField(
            model_name="opencostreport",
            name="warnings_count",
            field=models.IntegerField(
                default=0, help_text="Number of validation warnings in this report"
            ),
        ),
    ]
