# Generated by Django 6.0.8 on 2026-09-10 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("opencost", "0010_opencostreport_filters"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="opencostreport",
            name="xml_content",
        ),
    ]
