# Generated by Django 6.0.8 on 2026-09-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opencost", "0011_remove_opencostreport_xml_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="opencostreport",
            name="issues",
            field=models.JSONField(
                default=list,
                help_text="Validation issues as list of serialized ValidationWarning dicts",
            ),
        ),
        migrations.AddField(
            model_name="opencostreport",
            name="xml_content",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Generated openCost XML; empty string means nothing was exportable",
            ),
        ),
    ]
