# Generated by Django 6.0.8 on 2026-09-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opencost", "0012_add_opencostreport_xml_content_and_issues"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="opencostreportcontract",
            options={
                "ordering": ["id"],
                "verbose_name": "Report Contract",
                "verbose_name_plural": "Report Contracts",
            },
        ),
        migrations.AlterModelOptions(
            name="opencostreportcontractinvoice",
            options={
                "ordering": ["id"],
                "verbose_name": "Report Contract Invoice",
                "verbose_name_plural": "Report Contract Invoices",
            },
        ),
        migrations.AlterModelOptions(
            name="opencostreportinvoice",
            options={
                "ordering": ["id"],
                "verbose_name": "Report Invoice",
                "verbose_name_plural": "Report Invoices",
            },
        ),
        migrations.AlterModelOptions(
            name="opencostreportpublication",
            options={
                "ordering": ["id"],
                "verbose_name": "Report Publication",
                "verbose_name_plural": "Report Publications",
            },
        ),
        migrations.AddField(
            model_name="opencostreportcontract",
            name="exported",
            field=models.BooleanField(
                default=False, help_text="Whether this contract was included in the generated XML"
            ),
        ),
        migrations.AddField(
            model_name="opencostreportcontract",
            name="had_errors",
            field=models.BooleanField(
                default=False,
                help_text="Whether generation recorded an error-level issue for this contract",
            ),
        ),
        migrations.AddField(
            model_name="opencostreportcontract",
            name="xml_ordinal",
            field=models.IntegerField(
                blank=True,
                help_text="Index of this contract's entry in the generated XML; None when excluded",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="opencostreportcontractinvoice",
            name="exported",
            field=models.BooleanField(
                default=False, help_text="Whether this invoice was included in the generated XML"
            ),
        ),
        migrations.AddField(
            model_name="opencostreportcontractinvoice",
            name="had_errors",
            field=models.BooleanField(
                default=False,
                help_text="Whether generation recorded an error-level issue for this invoice",
            ),
        ),
        migrations.AddField(
            model_name="opencostreportcontractinvoice",
            name="xml_index",
            field=models.IntegerField(
                blank=True,
                help_text="Index of this invoice within its parent's exported invoices in the XML; None when excluded",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="opencostreportinvoice",
            name="exported",
            field=models.BooleanField(
                default=False, help_text="Whether this invoice was included in the generated XML"
            ),
        ),
        migrations.AddField(
            model_name="opencostreportinvoice",
            name="had_errors",
            field=models.BooleanField(
                default=False,
                help_text="Whether generation recorded an error-level issue for this invoice",
            ),
        ),
        migrations.AddField(
            model_name="opencostreportinvoice",
            name="xml_index",
            field=models.IntegerField(
                blank=True,
                help_text="Index of this invoice within its parent's exported invoices in the XML; None when excluded",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="opencostreportpublication",
            name="exported",
            field=models.BooleanField(
                default=False,
                help_text="Whether this publication was included in the generated XML",
            ),
        ),
        migrations.AddField(
            model_name="opencostreportpublication",
            name="had_errors",
            field=models.BooleanField(
                default=False,
                help_text="Whether generation recorded an error-level issue for this publication",
            ),
        ),
        migrations.AddField(
            model_name="opencostreportpublication",
            name="xml_ordinal",
            field=models.IntegerField(
                blank=True,
                help_text="Index of this publication's entry in the generated XML; None when excluded",
                null=True,
            ),
        ),
    ]
