# Generated by Django 6.0.1 on 2026-05-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FundingRequestCSVExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "filters",
                    models.JSONField(help_text="Filter criteria used to generate this export"),
                ),
                (
                    "record_count",
                    models.IntegerField(help_text="Number of rows in export at creation time"),
                ),
            ],
            options={
                "verbose_name": "Funding Request CSV Export",
                "verbose_name_plural": "Funding Request CSV Exports",
                "ordering": ["-created_at"],
            },
        ),
    ]
