# Generated by Django 6.0.1 on 2026-06-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundingrequestcsvexport",
            name="csv_file",
            field=models.FileField(blank=True, null=True, upload_to="fundingrequest_exports/"),
        ),
    ]
