# Generated by Django 6.0.1 on 2026-07-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exports", "0002_fundingrequestcsvexport_csv_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractCSVExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "filters",
                    models.JSONField(help_text="Filter criteria used to generate this export"),
                ),
                (
                    "record_count",
                    models.IntegerField(help_text="Number of rows in export at creation time"),
                ),
                (
                    "csv_file",
                    models.FileField(blank=True, null=True, upload_to="contract_exports/"),
                ),
            ],
            options={
                "verbose_name": "Contract CSV Export",
                "verbose_name_plural": "Contract CSV Exports",
                "ordering": ["-created_at"],
            },
        ),
    ]
