# Generated by Django 4.2.8 on 2024-05-22 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="positions",
        ),
        migrations.AddField(
            model_name="invoice",
            name="number",
            field=models.CharField(default="0", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="position",
            name="invoice",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="positions",
                to="invoices.invoice",
            ),
            preserve_default=False,
        ),
    ]
