# Generated by Django 4.2.8 on 2024-06-03 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0003_rename_recipient_invoice_creditor"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="date",
            field=models.DateField(default=datetime.date(2024, 6, 3)),
            preserve_default=False,
        ),
    ]
