# Generated by Django 4.2.8 on 2024-06-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0004_invoice_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="comment",
            field=models.TextField(blank=True),
        ),
    ]
