# Generated by Django 4.2.8 on 2024-06-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0005_invoice_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="tax_rate",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
