# Generated by Django 4.2.8 on 2024-06-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0006_position_tax_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="cost_type",
            field=models.CharField(default="other", max_length=255),
        ),
    ]
