# Generated by Django 4.2.8 on 2024-06-05 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0001_initial"),
        ("invoices", "0007_position_cost_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="publication",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="publications.publication",
            ),
        ),
    ]
