# Generated by Django 4.2.8 on 2024-06-06 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0008_alter_position_publication"),
    ]

    operations = [
        migrations.CreateModel(
            name="Creditor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="invoice",
            name="creditor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="invoices.creditor"
            ),
        ),
    ]
