# Generated by Django 5.1.3 on 2024-12-03 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_journals'),
        ('invoices', '0010_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.contract'),
        ),
    ]
