# Generated by Django 5.1.3 on 2024-12-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0011_position_contract"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="contract_year",
            field=models.IntegerField(null=True),
        ),
    ]
