# Generated by Django 5.1.3 on 2025-02-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0012_position_contract_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="external_invoice_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="position",
            name="external_position_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
