# Generated by Django 5.1.8 on 2025-06-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0013_invoice_external_invoice_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="cost_amount",
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
    ]
