# Generated by Django 5.1.8 on 2025-06-19 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0014_alter_position_cost_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrencyConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("target_currency", models.CharField(max_length=3)),
                ("exchange_rate", models.DecimalField(decimal_places=4, max_digits=11)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="currency_conversions",
                        to="invoices.invoice",
                    ),
                ),
            ],
        ),
    ]
