# Generated by Django 5.1.8 on 2025-07-08 13:55

from django.db import migrations

from coda.domain.invoice import ContractCostType, PublicationCostType


def migrate_contract_position_cost_type_to_publish(apps, schema_editor):
    Position = apps.get_model("invoices", "Position")
    Position.objects.filter(contract__isnull=False).update(cost_type=ContractCostType.Publish.value)


def migrate_backwards(apps, schema_editor):
    Position = apps.get_model("invoices", "Position")
    Position.objects.filter(contract__isnull=False).update(cost_type=PublicationCostType.Other.value)


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0015_currencyconversion"),
    ]

    operations = [migrations.RunPython(migrate_contract_position_cost_type_to_publish, migrate_backwards)]
