# Generated by Django 5.1.8 on 2025-10-15 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0002_institution_virtual"),
        ("invoices", "0016_contract_position_cost_type_to_publish"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundingsource",
            name="institution",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="institutions.institution",
            ),
        ),
        migrations.AddField(
            model_name="fundingsource",
            name="type",
            field=models.CharField(
                choices=[("budget", "Budget"), ("institution", "Institution")],
                default="budget",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="fundingsource",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
