# Generated by Django 5.1.8 on 2025-11-07 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0017_fundingsource_institution_fundingsource_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundingAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=4, max_digits=20)),
                (
                    "funding_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="funding_assignments",
                        to="invoices.fundingsource",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funding_assignments",
                        to="invoices.position",
                    ),
                ),
            ],
        ),
    ]
