# Generated by Django 5.1.8 on 2025-11-07 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0018_fundingassignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundingassignment",
            name="funding_source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="funding_assignments",
                to="invoices.fundingsource",
            ),
        ),
    ]
