# Generated by Django 5.1.8 on 2025-12-10 16:30

import logging

from django.db import migrations

logger = logging.getLogger(__name__)


def restore_funding_source_from_assignments(apps, schema_editor):
    """
    Reverse migration: Restore position.funding_source from FundingAssignment records.

    For each position with assignments:
    - Find first budget-type funding source (skip institution-type)
    - Set position.funding_source to that budget source
    - If no budget sources exist, leave as NULL

    Institution-type funding sources were introduced with the FundingAssignment
    feature and didn't exist in the old funding_source-only system, so they
    should not be restored to the funding_source field.
    """
    Position = apps.get_model("invoices", "Position")

    restored_count = 0

    for position in Position.objects.all().prefetch_related(
        "funding_assignments__funding_source"
    ):
        assignments = list(position.funding_assignments.all())

        if not assignments:
            continue

        budget_assignment = next(
            (
                a
                for a in assignments
                if a.funding_source and a.funding_source.type == "budget"
            ),
            None,
        )

        if budget_assignment:
            position.funding_source = budget_assignment.funding_source
            position.save(update_fields=["funding_source"])
            restored_count += 1

    logger.info(
        f"Restored funding_source for {restored_count} positions from assignments"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0020_migrate_funding_source_to_assignments"),
    ]

    operations = [
        migrations.RunPython(
            migrations.RunPython.noop,
            reverse_code=restore_funding_source_from_assignments,
        ),
        migrations.RemoveField(
            model_name="position",
            name="funding_source",
        ),
    ]
