# Generated by Django 6.0.5 on 2026-07-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0021_remove_position_funding_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[("paid", "paid"), ("unpaid", "unpaid"), ("rejected", "rejected")],
                default="unpaid",
                max_length=255,
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["paid", "unpaid", "rejected"])),
                name="invoice_status_valid",
            ),
        ),
    ]
