# Generated by Django 6.0.7 on 2026-07-14 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0022_add_status_choices_and_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditor',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='creditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoices.creditor'),
        ),
    ]
