# Generated by Django 6.0.7 on 2026-08-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0023_add_archived_at_to_creditor_and_protect_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingsource',
            name='budget_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
    ]
