# Generated by Django 6.0.8 on 2026-10-07 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0023_add_archived_at_to_creditor_and_protect_fk"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="position",
            options={"ordering": ("id",)},
        ),
    ]
