# Generated by Django 6.0.8 on 2026-10-07 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0024_alter_position_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fundingassignment",
            options={"ordering": ("id",)},
        ),
    ]
