version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  static_volume: {}

services:
  django:
    restart: always
    depends_on:
      - postgres

    image: coda_production_django
    build:
      context: .
      dockerfile: ./dockerfiles/production/django/Dockerfile

    expose:
      - 8000

    env_file:
      - ./.envs/.production/django.env
      - ./.envs/.production/postgres.env

    volumes:
      - static_volume:/app/staticfiles:rw

    command: /start

  postgres:
    restart: always
    image: coda_production_postgres
    build:
      context: .
      dockerfile: ./dockerfiles/production/postgres/Dockerfile

    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups

    environment:
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256

    env_file:
      - ./.envs/.production/postgres.env


  nginx:
    restart: always
    image: coda_production_nginx
    build:
      context: .
      dockerfile: ./dockerfiles/production/nginx/Dockerfile

    ports:
      - ${CODA_EXPOSED_PORT:-8000}:80

    depends_on:
      - django

    volumes:
      - static_volume:/usr/share/nginx/static/
