version: "3"

volumes:
  coda_local_postgres_data: {}

services:
  django:
    build:
      context: .
      dockerfile: ./dockerfiles/local/Dockerfile.devcontainer

    image: coda_local_django
    container_name: coda_local_django
    depends_on:
      - postgres

    volumes:
      - .:/app:z

    env_file:
      - ./.envs/.local/django.env
      - ./.envs/.local/postgres.env

    ports:
      - "8000:8000"

    command: >
      sh -c "pdm run manage.py migrate && pdm run manage.py runserver"

  postgres:
    image: postgres:13.1-alpine
    container_name: coda_local_postgres

    volumes:
      - coda_local_postgres_data:/var/lib/postgresql/data/

    env_file:
      - ./.envs/.local/postgres.env
