volumes:
  coda_local_postgres_data: {}
  coda_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./dockerfiles/local/Dockerfile.devcontainer

    image: coda_local_django
    container_name: coda_local_django
    depends_on:
      - postgres

    volumes:
      - .:/app:z

    env_file:
      - ./.envs/.local/django.env
      - ./.envs/.local/postgres.env

    ports:
      - 8000:8000

    entrypoint: [ "/bin/sh", "/entrypoint" ]

    command: /start

  postgres:
    image: coda_local_postgres:${POSTGRES_VERSION}
    container_name: coda_local_postgres
    build:
      context: .
      dockerfile: ./dockerfiles/production/postgres/Dockerfile
      args:
          POSTGRES_VERSION: ${POSTGRES_VERSION}

    volumes:
      - coda_local_postgres_data:/var/lib/postgresql/data/
      - coda_local_postgres_data_backups:/backups

    env_file:
      - ./.envs/.local/postgres.env
