# Generated by Django 5.0.7 on 2024-07-16 09:33

import coda.apps.preferences.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("publications", "0009_publication_subject_area_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("home_currency", models.CharField(default="EUR", max_length=255)),
                (
                    "default_publication_type_vocabulary",
                    models.ForeignKey(
                        default=coda.apps.preferences.models.empty_vocabulary,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="+",
                        to="publications.vocabulary",
                    ),
                ),
                (
                    "default_subject_classification_vocabulary",
                    models.ForeignKey(
                        default=coda.apps.preferences.models.empty_vocabulary,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="+",
                        to="publications.vocabulary",
                    ),
                ),
            ],
        ),
    ]
