# Generated by Django 5.0.7 on 2024-07-17 10:43

import coda.apps.publications.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preferences", "0001_initial"),
        ("publications", "0009_publication_subject_area_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalpreferences",
            name="default_publication_type_vocabulary",
            field=models.ForeignKey(
                default=coda.apps.publications.models.Vocabulary.empty,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="+",
                to="publications.vocabulary",
            ),
        ),
        migrations.AlterField(
            model_name="globalpreferences",
            name="default_subject_classification_vocabulary",
            field=models.ForeignKey(
                default=coda.apps.publications.models.Vocabulary.empty,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="+",
                to="publications.vocabulary",
            ),
        ),
    ]
