# Generated by Django 5.0.7 on 2024-09-04 09:56

import coda.apps.preferences.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "preferences",
            "0002_alter_globalpreferences_default_publication_type_vocabulary_and_more",
        ),
        ("publications", "0009_publication_subject_area_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalpreferences",
            name="default_publication_type_vocabulary",
            field=models.ForeignKey(
                default=coda.apps.preferences.models.default_publication_type_vocabulary,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="+",
                to="publications.vocabulary",
            ),
        ),
        migrations.AlterField(
            model_name="globalpreferences",
            name="default_subject_classification_vocabulary",
            field=models.ForeignKey(
                default=coda.apps.preferences.models.default_subject_classification_vocabulary,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="+",
                to="publications.vocabulary",
            ),
        ),
    ]
