# Generated by Django 5.0.7 on 2024-09-04 09:56

import django.db.models.deletion
from django.db import migrations, models


def set_default_vocabularies(apps, schema_editor):
    """
    Set default vocabulary values for existing GlobalPreferences instances.
    Uses historical models to avoid referencing fields that may not exist yet.
    """
    GlobalPreferences = apps.get_model('preferences', 'GlobalPreferences')
    Vocabulary = apps.get_model('publications', 'Vocabulary')
    Concept = apps.get_model('publications', 'Concept')
    
    # Hardcoded constants from coda.domain.vocabulary
    # Using hardcoded values avoids importing domain code which could reference
    # model fields that don't exist yet in the database schema
    EMPTY_VOCABULARY_ID = 0
    UNKNOWN_CONCEPT_UUID = "fd0febd8-2218-4327-a517-d78b7f8f58ff"
    
    # Ensure empty vocabulary exists
    empty_vocab, _ = Vocabulary.objects.get_or_create(
        pk=EMPTY_VOCABULARY_ID,
        defaults={'name': 'empty vocabulary', 'version': ''}
    )
    
    # Ensure unknown concept exists
    # At this migration point (0003), the Concept model does NOT have a parent field yet
    # (parent field is added in publications/0045_concept_parent)
    # So we only set fields that definitely exist: concept_id, vocabulary, name, hint
    Concept.objects.get_or_create(
        concept_id=UNKNOWN_CONCEPT_UUID,
        vocabulary=empty_vocab,
        defaults={'name': 'unknown', 'hint': ''}
    )
    
    # Find specific vocabularies or use empty as fallback
    coar_vocab = Vocabulary.objects.filter(name="COAR Resource Types").first()
    dfg_vocab = Vocabulary.objects.filter(name="DFG Subject Classification").first()
    
    pub_vocab_id = coar_vocab.id if coar_vocab else EMPTY_VOCABULARY_ID
    subj_vocab_id = dfg_vocab.id if dfg_vocab else EMPTY_VOCABULARY_ID
    
    # Update any existing GlobalPreferences instances
    for prefs in GlobalPreferences.objects.all():
        prefs.default_publication_type_vocabulary_id = pub_vocab_id
        prefs.default_subject_classification_vocabulary_id = subj_vocab_id
        prefs.save()


class Migration(migrations.Migration):

    dependencies = [
        (
            "preferences",
            "0002_alter_globalpreferences_default_publication_type_vocabulary_and_more",
        ),
        ("publications", "0009_publication_subject_area_and_more"),
    ]

    operations = [
        # First, alter fields to temporarily allow null and use None as default
        # This allows us to create/alter the field structure before setting actual values
        migrations.AlterField(
            model_name="globalpreferences",
            name="default_publication_type_vocabulary",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="publications.vocabulary",
            ),
        ),
        migrations.AlterField(
            model_name="globalpreferences",
            name="default_subject_classification_vocabulary",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="publications.vocabulary",
            ),
        ),
        # Now use RunPython to set the actual default values using historical models
        # This ensures we only access database columns that exist at this migration point
        migrations.RunPython(
            set_default_vocabularies,
            reverse_code=migrations.RunPython.noop
        ),
        # Finally, change fields to use SET_DEFAULT behavior with hardcoded default
        # Using integer 0 instead of a callable avoids executing model code during migration
        migrations.AlterField(
            model_name="globalpreferences",
            name="default_publication_type_vocabulary",
            field=models.ForeignKey(
                default=0,  # Hardcoded EMPTY_VOCABULARY_ID
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="+",
                to="publications.vocabulary",
            ),
        ),
        migrations.AlterField(
            model_name="globalpreferences",
            name="default_subject_classification_vocabulary",
            field=models.ForeignKey(
                default=0,  # Hardcoded EMPTY_VOCABULARY_ID
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="+",
                to="publications.vocabulary",
            ),
        ),
    ]
