# Generated by Django 5.1.3 on 2024-12-12 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "preferences",
            "0003_alter_globalpreferences_default_publication_type_vocabulary_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="globalpreferences",
            old_name="default_subject_classification_vocabulary",
            new_name="subject_classification_vocabulary",
        ),
    ]
