# Generated by Django 5.1.3 on 2024-12-12 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "preferences",
            "0004_rename_default_subject_classification_vocabulary_globalpreferences_subject_classification_vocabulary",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="globalpreferences",
            old_name="default_publication_type_vocabulary",
            new_name="article_publication_type_vocabulary",
        ),
    ]
