# Generated by Django 5.1.3 on 2024-12-12 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "preferences",
            "0005_rename_default_publication_type_vocabulary_globalpreferences_article_publication_type_vocabulary",
        ),
        ("publications", "0029_publication_monograph_publisher"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalpreferences",
            name="monograph_publication_type_vocabulary",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="publications.vocabulary",
            ),
        ),
    ]
