# Generated by Django 5.1.3 on 2024-12-12 09:13

import coda.apps.preferences.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preferences", "0006_globalpreferences_monograph_publication_type_vocabulary"),
        ("publications", "0029_publication_monograph_publisher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalpreferences",
            name="monograph_publication_type_vocabulary",
            field=models.ForeignKey(
                default=coda.apps.preferences.models.default_publication_type_vocabulary,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="+",
                to="publications.vocabulary",
            ),
        ),
    ]
