# Generated by Django 5.1.3 on 2024-12-12 09:13

import django.db.models.deletion
from django.db import migrations, models


def set_monograph_vocabulary_default(apps, schema_editor):
    """
    Set default monograph vocabulary for existing GlobalPreferences instances.
    Uses historical models to avoid referencing fields that may not exist yet.
    """
    GlobalPreferences = apps.get_model('preferences', 'GlobalPreferences')
    Vocabulary = apps.get_model('publications', 'Vocabulary')
    Concept = apps.get_model('publications', 'Concept')
    
    # Hardcoded constants from coda.domain.vocabulary
    # Using hardcoded values avoids importing domain code which could reference
    # model fields that don't exist yet in the database schema
    EMPTY_VOCABULARY_ID = 0
    UNKNOWN_CONCEPT_UUID = "fd0febd8-2218-4327-a517-d78b7f8f58ff"
    
    # Ensure empty vocabulary exists
    empty_vocab, _ = Vocabulary.objects.get_or_create(
        pk=EMPTY_VOCABULARY_ID,
        defaults={'name': 'empty vocabulary', 'version': ''}
    )
    
    # Ensure unknown concept exists
    # IMPORTANT: At this migration point (0007), the parent field status is UNCERTAIN
    # because publications/0045_concept_parent is in a parallel migration branch.
    # We use get_or_create and only set fields that we KNOW exist.
    # We deliberately DO NOT set the parent field as it may not exist yet.
    Concept.objects.get_or_create(
        concept_id=UNKNOWN_CONCEPT_UUID,
        vocabulary=empty_vocab,
        defaults={'name': 'unknown', 'hint': ''}
    )
    
    # Find COAR vocabulary or use empty as fallback
    coar_vocab = Vocabulary.objects.filter(name="COAR Resource Types").first()
    vocab_id = coar_vocab.id if coar_vocab else EMPTY_VOCABULARY_ID
    
    # Update existing GlobalPreferences instances
    for prefs in GlobalPreferences.objects.all():
        if prefs.monograph_publication_type_vocabulary_id is None:
            prefs.monograph_publication_type_vocabulary_id = vocab_id
            prefs.save()


class Migration(migrations.Migration):

    dependencies = [
        ("preferences", "0006_globalpreferences_monograph_publication_type_vocabulary"),
        ("publications", "0029_publication_monograph_publisher"),
    ]

    operations = [
        # First, ensure the field allows null temporarily
        # (0006 already created it as nullable, so this might be redundant but is safe)
        migrations.AlterField(
            model_name="globalpreferences",
            name="monograph_publication_type_vocabulary",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="publications.vocabulary",
            ),
        ),
        # Use RunPython to set defaults using historical models
        # This ensures we only access database columns that exist at this migration point
        migrations.RunPython(
            set_monograph_vocabulary_default,
            reverse_code=migrations.RunPython.noop
        ),
        # Finally, change to SET_DEFAULT behavior with hardcoded default
        # Using integer 0 instead of a callable avoids executing model code during migration
        migrations.AlterField(
            model_name="globalpreferences",
            name="monograph_publication_type_vocabulary",
            field=models.ForeignKey(
                default=0,  # Hardcoded EMPTY_VOCABULARY_ID
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="+",
                to="publications.vocabulary",
            ),
        ),
    ]
