# Generated by Django 5.1.8 on 2025-11-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preferences", "0007_alter_globalpreferences_monograph_publication_type_vocabulary"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalpreferences",
            name="home_institution_identifier",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Primary institution identifier (ROR, ISNI, or Ringold)",
                max_length=500,
            ),
        ),
    ]
