# Generated by Django 5.1.8 on 2025-12-02 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0003_add_institution_links"),
        ("preferences", "0008_add_home_institution_identifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalpreferences",
            name="home_institution",
            field=models.ForeignKey(
                blank=True,
                help_text="Home institution",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="institutions.institution",
            ),
        ),
        migrations.AlterField(
            model_name="globalpreferences",
            name="home_institution_identifier",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Primary institution identifier (ROR, ISNI, or Ringold) - DEPRECATED: Use home_institution instead",
                max_length=500,
            ),
        ),
    ]
