# Generated by Django 5.1.8 on 2025-12-02 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("preferences", "0009_globalpreferences_home_institution_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="globalpreferences",
            name="home_institution_identifier",
        ),
    ]
