# Generated by Django 5.1.8 on 2026-01-22 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preferences", "0010_remove_home_institution_identifier"),
        ("publications", "0047_merge_20260112_0843"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalpreferences",
            name="article_publication_type_vocabulary",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="publications.vocabulary",
            ),
        ),
        migrations.AlterField(
            model_name="globalpreferences",
            name="monograph_publication_type_vocabulary",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="publications.vocabulary",
            ),
        ),
        migrations.AlterField(
            model_name="globalpreferences",
            name="subject_classification_vocabulary",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="publications.vocabulary",
            ),
        ),
    ]
