FUNDINGREQUEST_LIST = "#fundingrequest-list"
INVOICE_LIST = "#invoice-list"

ACTIVE_FILTERS = "#active-filters"
ACTIVE_FILTER = ".active-filter"
ACTIVE_FILTER_REMOVE = ".active-filter-remove"
FILTER_SEARCH = ".filter-search"
FILTER_SORT = "#sort_by"
FILTER_DRAWER_TOGGLE = "#filter-drawer-toggle"
FILTER_DRAWER_CLOSE = "#filter-drawer-close"
FILTER_SIDEBAR = "#filter-sidebar"
FILTER_SIDEBAR_CLASS = ".filter-sidebar"
FILTER_LAYOUT = ".filter-layout"
FILTER_COUNT_BADGE = "#filter-sidebar-header .filter-count"
FILTER_CLEAR_ALL = "#filter-sidebar-header .filter-clear"
TOOLBAR_FILTER_COUNT = "#toolbar-filter-count"
HTMX_REQUEST = ".htmx-request"
LABEL_FILTER_PILL = ".label-filter-pill"
SEARCH_SELECT_MULTI_INPUT = ".search-input"
SEARCH_SELECT_OPTION = ".option"
HTMX_IDLE_EXPRESSION = f"() => !document.querySelector({HTMX_REQUEST!r})"

CONTRACT_NAME = "#contract_name"
CONTRACT_YEAR = "#contract_year"
DATE_START = "#date_start"
HAS_ERRORS = "#has_errors"
ID_PAYMENT_STATUS = "#id_payment_status"
INVALID_CONTRACT_YEARS = "#invalid_contract_years"
PAYMENT_STATUS = "#payment_status"
PROCESSING_STATUS = "#processing_status"
PUBLICATION_TYPE_ALL = "#publication_type_all"
PUBLICATION_TYPE_ARTICLE = "#publication_type_article"
SEARCH_SELECT_OPTION_ITEM = "li"
SEARCH_SELECT_BOX = "#search-box"
SELECTED_TAG = ".selected-tag"
