# Generated by Django 4.2.8 on 2024-01-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="licenses",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
