# Generated by Django 4.2.8 on 2024-01-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journals", "0002_alter_journal_licenses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="open_access_type",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
