# Generated by Django 4.2.8 on 2024-06-19 09:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("journals", "0002_alter_journal_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journal",
            name="open_access_type",
        ),
    ]
