# Generated by Django 4.2.8 on 2024-01-19 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("publishers", "0001_initial"),
        ("journals", "0003_alter_journal_open_access_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="publisher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journals",
                to="publishers.publisher",
            ),
        ),
        migrations.DeleteModel(
            name="Publisher",
        ),
    ]
