# Generated by Django 4.2.8 on 2024-01-19 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("journals", "0004_alter_journal_publisher_delete_publisher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="successor_to",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="predecessor",
                to="journals.journal",
            ),
        ),
    ]
