# Generated by Django 4.2.8 on 2024-01-19 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("journals", "0005_alter_journal_successor_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journal",
            name="successor_to",
        ),
        migrations.AddField(
            model_name="journal",
            name="predecessor",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="successor",
                to="journals.journal",
            ),
        ),
    ]
