# Generated by Django 5.1.3 on 2025-01-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="virtual",
            field=models.BooleanField(default=False),
        ),
    ]
