# Generated by Django 6.0.1 on 2026-03-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0003_add_institution_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="archived_at",
            field=models.DateTimeField(
                blank=True, db_index=True, help_text="When this institution was archived", null=True
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="succeeded_by",
            field=models.ManyToManyField(
                blank=True,
                help_text="The institution(s) that succeeded this one",
                related_name="predecessor_of",
                to="institutions.institution",
            ),
        ),
    ]
