# Generated by Django 6.0.1 on 2026-03-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0004_institution_archived_at_institution_succeeded_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="internal_id",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Stable identifier for import/export matching",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
    ]
