# Generated by Django 6.0.1 on 2026-04-01 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0005_add_internal_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="institution",
            name="succeeded_by",
        ),
    ]
