# Generated by Django 6.0.1 on 2026-05-11 16:01

import uuid
from django.db import migrations, models


def populate_node_ids_and_paths(apps, schema_editor):
    Institution = apps.get_model("institutions", "Institution")

    # Assign a unique node_id to every existing institution
    for inst in Institution.objects.all():
        inst.node_id = uuid.uuid4()
        inst.save(update_fields=["node_id"])

    # Compute paths iteratively top-down (roots first, then children level by level)
    all_institutions = {inst.pk: inst for inst in Institution.objects.all()}

    # Seed the queue with root institutions
    queue = [inst for inst in all_institutions.values() if inst.parent_id is None]
    for inst in queue:
        inst.path = f"/{inst.node_id}/"

    while queue:
        next_queue = []
        for inst in queue:
            for child in Institution.objects.filter(parent_id=inst.pk):
                child = all_institutions[child.pk]
                child.path = inst.path + str(child.node_id) + "/"
                next_queue.append(child)
        queue = next_queue

    if all_institutions:
        Institution.objects.bulk_update(all_institutions.values(), ["path"])


class Migration(migrations.Migration):
    # Must be non-atomic so we can ALTER TABLE after RunPython within the same migration.
    # PostgreSQL does not allow altering a table with pending FK trigger events inside
    # a single transaction that also performed DML on that table.
    atomic = False

    dependencies = [
        ("institutions", "0006_remove_succeeded_by_field"),
    ]

    operations = [
        # Step 1: add node_id without unique constraint so existing rows accept a null default
        migrations.AddField(
            model_name="institution",
            name="node_id",
            field=models.UUIDField(null=True, editable=False),
        ),
        # Step 2: add path field
        migrations.AddField(
            model_name="institution",
            name="path",
            field=models.CharField(db_index=True, default="", max_length=500),
        ),
        # Step 3: populate unique node_ids and paths for all existing rows
        migrations.RunPython(populate_node_ids_and_paths, migrations.RunPython.noop),
        # Step 4: make node_id non-nullable and unique now that all rows have values
        migrations.AlterField(
            model_name="institution",
            name="node_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
