# Generated by Django 6.0.1 on 2026-05-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutions", "0007_add_node_id_and_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="institution",
            name="path",
        ),
        migrations.RemoveField(
            model_name="institution",
            name="node_id",
        ),
    ]
