# Generated by Django 6.0.8 on 2026-09-17 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0009_rename_ringold_link_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="institutionlinktype",
            options={"ordering": ["name"]},
        ),
    ]
