# Generated by Django 4.2.8 on 2024-02-12 12:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("publications", "0003_publication_submitting_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "hexcolor",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Color must be in the format #RRGGBB",
                                regex="^#[a-fA-F0-9]{6}$",
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FundingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "request_id",
                    models.CharField(default="coda-adc5d4-2024-02-12", max_length=23, unique=True),
                ),
                ("estimated_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("estimated_cost_currency", models.CharField(max_length=3)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("in_progress", "In Progress"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "labels",
                    models.ManyToManyField(related_name="requests", to="fundingrequests.label"),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="publications.publication"
                    ),
                ),
            ],
        ),
    ]
