# Generated by Django 4.2.8 on 2024-05-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fundingrequests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundingrequest",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("open", "In Progress"),
                    ("rejected", "Rejected"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
