# Generated by Django 4.2.8 on 2024-02-14 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("fundingrequests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundingrequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fundingrequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="fundingrequest",
            name="request_id",
            field=models.CharField(default="coda-709524-2024-02-14", max_length=23, unique=True),
        ),
    ]
