# Generated by Django 4.2.8 on 2024-02-20 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authors", "0004_alter_author_affiliation"),
        ("fundingrequests", "0002_fundingrequest_created_at_fundingrequest_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundingrequest",
            name="submitter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="funding_requests",
                to="authors.author",
            ),
        ),
        migrations.AlterField(
            model_name="fundingrequest",
            name="request_id",
            field=models.CharField(default="coda-27c372-2024-02-20", max_length=23, unique=True),
        ),
    ]
