# Generated by Django 4.2.8 on 2024-05-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fundingrequests", "0002_alter_fundingrequest_processing_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundingrequest",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Direct", "Direct"),
                    ("Reimbursement", "Reimbursement"),
                    ("Unknown", "Unknown"),
                ],
                default="Unknown",
            ),
        ),
        migrations.AlterField(
            model_name="fundingrequest",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("Approved", "Approved"),
                    ("Open", "In Progress"),
                    ("Rejected", "Rejected"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
