# Generated by Django 4.2.8 on 2024-02-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fundingrequests", "0003_fundingrequest_submitter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundingrequest",
            name="request_id",
            field=models.CharField(default="coda-a22c47-2024-02-20", max_length=23, unique=True),
        ),
    ]
