# Generated by Django 4.2.8 on 2024-05-29 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0001_initial"),
        ("fundingrequests", "0005_alter_fundingrequest_estimated_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundingrequest",
            name="publication",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="publications.publication"
            ),
        ),
    ]
