# Generated by Django 4.2.8 on 2024-02-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fundingrequests", "0005_alter_fundingrequest_processing_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundingrequest",
            name="request_id",
            field=models.CharField(default="coda-e72c6c0a-2024-02-26", max_length=25, unique=True),
        ),
    ]
