# Generated by Django 5.0.7 on 2024-10-17 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundingrequests", "0006_alter_fundingrequest_publication"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fundingrequest",
            name="external_funding",
        ),
        migrations.AddField(
            model_name="externalfunding",
            name="funding_request",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="external_funding",
                to="fundingrequests.fundingrequest",
            ),
        ),
    ]
