# Generated by Django 5.1.3 on 2024-12-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundingrequests", "0007_remove_fundingrequest_external_funding_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundingrequest",
            name="review_decided_funding_amount",
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="fundingrequest",
            name="review_decided_funding_currency",
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="fundingrequest",
            name="review_remarks",
            field=models.TextField(blank=True),
        ),
    ]
