# Generated by Django 5.1.3 on 2025-01-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundingrequests", "0008_fundingrequest_review_decided_funding_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundingRequestContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField()),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
