# Generated by Django 4.2.8 on 2024-02-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fundingrequests", "0008_alter_fundingrequest_request_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundingrequest",
            name="request_id",
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
