# Generated by Django 4.2.8 on 2024-04-02 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fundingrequests", "0009_alter_fundingrequest_request_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundingOrganization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="ExternalFunding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("project_id", models.CharField()),
                ("project_name", models.CharField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fundingrequests.fundingorganization",
                    ),
                ),
            ],
        ),
    ]
