# Generated by Django 5.1.3 on 2025-01-29 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0003_author_publication"),
        ("fundingrequests", "0009_fundingrequestcontact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundingrequest",
            name="submitter",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="funding_requests",
                to="authors.author",
            ),
        ),
    ]
