# Generated by Django 4.2.8 on 2024-04-02 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fundingrequests", "0010_fundingorganization_externalfunding"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundingrequest",
            name="external_funding",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="fundingrequests.externalfunding",
            ),
        ),
    ]
