# Generated by Django 5.1.3 on 2025-01-29 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundingrequests", "0011_alter_fundingrequest_submitter"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundingrequest",
            name="extra_contact",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="fundingrequests.fundingrequestcontact",
            ),
        ),
    ]
