# Generated by Django 5.1.3 on 2025-01-29 13:35

from django.db import migrations


def convert_submitter_to_contact(apps, schema_editor):
    FundingRequest = apps.get_model("fundingrequests", "FundingRequest")
    FundingRequestContact = apps.get_model("fundingrequests", "FundingRequestContact")

    for request in FundingRequest.objects.all():
        contact = FundingRequestContact.objects.create(
            name=request.submitter.name, email=request.submitter.email
        )
        request.contact = contact
        request.save()


class Migration(migrations.Migration):

    dependencies = [
        ("fundingrequests", "0012_fundingrequest_extra_contact"),
    ]

    operations = [migrations.RunPython(convert_submitter_to_contact, migrations.RunPython.noop)]
