# Generated by Django 5.1.3 on 2025-01-29 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundingrequests", "0013_fundingrequest_submitter_to_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundingrequest",
            name="extra_contact",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="funding_request",
                to="fundingrequests.fundingrequestcontact",
            ),
        ),
    ]
