# Generated by Django 5.1.3 on 2025-01-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fundingrequests", "0014_alter_fundingrequest_extra_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fundingrequest",
            name="submitter",
        ),
    ]
