# Generated by Django 5.1.3 on 2025-01-30 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundingrequests", "0015_remove_fundingrequest_submitter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundingrequest",
            name="extra_contact",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="funding_request",
                to="fundingrequests.fundingrequestcontact",
            ),
        ),
    ]
