# Generated by Django 5.1.3 on 2025-02-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundingrequests", "0016_alter_fundingrequest_extra_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundingrequest",
            name="request_id",
            field=models.CharField(max_length=26, unique=True),
        ),
    ]
