# Generated by Django 5.1.3 on 2025-02-18 09:18

from django.db import migrations

from coda.fundingrequest.identity import PublicFundingRequestId


def assign_new_fundingrequest_id(apps, schema_editor):
    FundingRequest = apps.get_model("fundingrequests", "FundingRequest")
    for fr in FundingRequest.objects.all():
        fr.request_id = try_parse_id_or_new(fr)
        fr.save()


def try_parse_id_or_new(fr):
    try:
        id = PublicFundingRequestId.from_str(fr.request_id)
    except ValueError:
        id = PublicFundingRequestId.create(fr.created_at)

    return id


class Migration(migrations.Migration):

    dependencies = [
        ("fundingrequests", "0017_alter_fundingrequest_request_id"),
    ]

    operations = [migrations.RunPython(assign_new_fundingrequest_id, migrations.RunPython.noop)]
