# Generated by Django 5.1.3 on 2025-02-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundingrequests", "0018_assign_new_fundingrequest_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundingrequest",
            name="request_remarks",
            field=models.TextField(blank=True),
        ),
    ]
