# Generated by Django 5.1.6 on 2025-03-05 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundingrequests", "0019_fundingrequest_request_remarks"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundingRequestReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("review_result", models.CharField(default="open", max_length=20)),
                (
                    "decided_funding_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("decided_funding_currency", models.CharField(blank=True, max_length=3)),
                ("remarks", models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="fundingrequest",
            name="review",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fundingrequest",
                to="fundingrequests.fundingrequestreview",
            ),
        ),
    ]
