# Generated by Django 5.1.6 on 2025-03-05 14:13

from django.db import migrations


def migrate_to_review_result(apps, schema_editor):
    FundingRequest = apps.get_model("fundingrequests", "FundingRequest")
    FundingRequestReview = apps.get_model("fundingrequests", "FundingRequestReview")

    for fr in FundingRequest.objects.all():
        review = FundingRequestReview.objects.create(
            review_result=fr.processing_status,
            decided_funding_amount=fr.review_decided_funding_amount or 0,
            decided_funding_currency=fr.review_decided_funding_currency or "",
            remarks=fr.review_remarks,
        )

        fr.review = review
        fr.save()


def revert_to_processing_status(apps, schema_editor):
    FundingRequest = apps.get_model("fundingrequests", "FundingRequest")
    FundingRequestReview = apps.get_model("fundingrequests", "FundingRequestReview")

    for fr in FundingRequest.objects.all():
        review = FundingRequestReview.objects.get(funding_request=fr)
        fr.processing_status = review.review_result
        fr.review_decided_funding_amount = review.decided_funding_amount
        fr.review_decided_funding_currency = review.decided_funding_currency
        fr.review_request_remarks = review.remarks
        fr.save()
        review.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("fundingrequests", "0020_fundingrequestreview_fundingrequest_review"),
    ]

    operations = [migrations.RunPython(migrate_to_review_result, revert_to_processing_status)]
