# Generated by Django 5.1.6 on 2025-03-05 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fundingrequests", "0021_assign_review_data_to_fundingrequestreview"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fundingrequest",
            name="processing_status",
        ),
        migrations.RemoveField(
            model_name="fundingrequest",
            name="review_decided_funding_amount",
        ),
        migrations.RemoveField(
            model_name="fundingrequest",
            name="review_decided_funding_currency",
        ),
        migrations.RemoveField(
            model_name="fundingrequest",
            name="review_remarks",
        ),
    ]
