# Generated by Django 5.1.6 on 2025-03-05 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundingrequests", "0022_remove_fundingrequest_processing_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundingrequest",
            name="review",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fundingrequest",
                to="fundingrequests.fundingrequestreview",
            ),
        ),
    ]
