# Generated by Django 5.1.6 on 2025-03-05 16:45

from django.db import migrations


def ensure_fundingrequestreview_present(apps, schema_editor):
    FundingRequest = apps.get_model("fundingrequests", "FundingRequest")
    FundingRequestReview = apps.get_model("fundingrequests", "FundingRequestReview")

    for fr in FundingRequest.objects.all():
        if fr.review is None:
            review = FundingRequestReview.objects.create()
            fr.review = review
            fr.save()


class Migration(migrations.Migration):

    dependencies = [
        ("fundingrequests", "0023_alter_fundingrequest_review"),
    ]

    operations = [
        migrations.RunPython(ensure_fundingrequestreview_present, migrations.RunPython.noop)
    ]
