# Generated by Django 5.1.8 on 2025-05-02 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundingrequests', '0024_ensure_fundingrequestreview_present'),
        ('publications', '0043_alter_publicationpayment_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingrequest',
            name='publication',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fundingrequest', to='publications.publication'),
        ),
    ]
