# Generated by Django 5.1.8 on 2025-06-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundingrequests", "0025_alter_fundingrequest_publication"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundingrequest",
            name="request_date",
            field=models.DateField(null=True),
        ),
    ]
