# Generated by Django 5.1.8 on 2025-06-17 14:17

from django.db import migrations

from coda.domain.fundingrequest.identity import PublicFundingRequestId


def populate_request_date(apps, schema_editor):
    FundingRequest = apps.get_model("fundingrequests", "FundingRequest")
    for fundingrequest in FundingRequest.objects.all():
        request_id = PublicFundingRequestId.from_str(fundingrequest.request_id)
        fundingrequest.request_date = request_id.date()
        fundingrequest.save()


class Migration(migrations.Migration):

    dependencies = [
        ("fundingrequests", "0026_fundingrequest_request_date"),
    ]

    operations = [migrations.RunPython(populate_request_date, migrations.RunPython.noop)]
