# Generated by Django 5.1.8 on 2025-06-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundingrequests", "0027_populate_request_date_from_request_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundingrequest",
            name="request_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
