# Generated by Django 5.1.8 on 2025-06-17 14:28

from django.db import migrations

from coda.domain.fundingrequest.identity import PublicFundingRequestId

def populate_request_number(apps, schema_editor):
    FundingRequest = apps.get_model("fundingrequests", "FundingRequest")
    for fundingrequest in FundingRequest.objects.all():
        request_id = PublicFundingRequestId.from_str(fundingrequest.request_id)
        fundingrequest.request_number = request_id.id_without_checksum()
        fundingrequest.save()


class Migration(migrations.Migration):

    dependencies = [
        ("fundingrequests", "0028_fundingrequest_request_number"),
    ]

    operations = [migrations.RunPython(populate_request_number, migrations.RunPython.noop)]
