# Generated by Django 5.1.8 on 2025-06-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundingrequests", "0029_populate_request_number_from_request_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundingrequest",
            name="request_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="fundingrequest",
            name="request_number",
            field=models.CharField(max_length=20),
        ),
    ]
