# Generated by Django 5.1.8 on 2025-07-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundingrequests", "0030_alter_fundingrequest_request_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundingrequest",
            name="legacy_request_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
