# Generated by Django 5.1.8 on 2026-01-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundingrequests", "0031_fundingrequest_legacy_request_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundingrequest",
            name="external_costsplitting",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="True if cost splitting occurred, None/null if unknown (omitted in OpenCost)",
                null=True,
            ),
        ),
    ]
