# Generated by Django 5.1.8 on 2026-01-09 09:21

from django.db import migrations

def move_cost_splitting(apps, schema_editor):
    funding_request_model = apps.get_model("fundingrequests", "FundingRequest")
    
    for fr in funding_request_model.objects.select_related('publication').all():
        if fr.publication:
            fr.external_costsplitting = fr.publication.external_costsplitting
            fr.save(update_fields=["external_costsplitting"])



class Migration(migrations.Migration):

    dependencies = [
        ("fundingrequests", "0032_fundingrequest_external_costsplitting"),
    ]

    operations = [
        migrations.RunPython(move_cost_splitting),
    ]
