# Generated by Django 6.0.7 on 2026-07-17 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundingrequests', '0036_seed_crossref_link_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingorganization',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='externalfunding',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fundingrequests.fundingorganization'),
        ),
    ]
