# Generated by Django 4.2.8 on 2024-03-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("publishers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("start_date", models.DateField(null=True)),
                ("end_date", models.DateField(null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "publishers",
                    models.ManyToManyField(related_name="contracts", to="publishers.publisher"),
                ),
            ],
        ),
    ]
