# Generated by Django 4.2.8 on 2024-06-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journals", "0003_remove_journal_open_access_type"),
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="journals",
            field=models.ManyToManyField(related_name="contracts", to="journals.journal"),
        ),
    ]
