# Generated by Django 4.2.8 on 2024-03-28 11:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contract",
            old_name="is_active",
            new_name="active_status",
        ),
    ]
