# Generated by Django 5.1.3 on 2025-02-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_journals'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='publication_billing',
            field=models.CharField(default='individually', max_length=255),
            preserve_default=False,
        ),
    ]
