# Generated by Django 4.2.8 on 2024-01-30 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='author_entries',
        ),
        migrations.AddField(
            model_name='author',
            name='details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authored_publications', to='authors.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='orcid',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
