# Generated by Django 5.1.3 on 2025-01-27 08:04

import enum
from collections.abc import Iterable

from django.db import migrations


# State of Role enum at the time of migration
class Role(enum.Enum):
    SUBMITTER = "Submitter"
    CO_AUTHOR = "Co-author"
    CORRESPONDING_AUTHOR = "Corresponding author"


ROLE_SERIALIZE_SEPARATOR = "||"


def deserialize_roles(serialized: str) -> Iterable[Role]:
    return (Role[role] for role in serialized.split(ROLE_SERIALIZE_SEPARATOR))


def pick_highest_role(roles: Iterable[Role]) -> Role:
    if not roles:
        return Role.CO_AUTHOR

    if Role.CORRESPONDING_AUTHOR in roles:
        return Role.CORRESPONDING_AUTHOR

    if Role.SUBMITTER in roles:
        return Role.SUBMITTER

    return Role.CO_AUTHOR


def migrate_roles(apps, schema_editor):
    Author = apps.get_model("authors", "Author")
    for author in Author.objects.all():
        if not author.roles:
            author.roles = Role.CO_AUTHOR.name
        else:
            roles = deserialize_roles(author.roles)
            author.roles = pick_highest_role(roles).name
        author.save()


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(migrate_roles, reverse_code=migrations.RunPython.noop),
    ]
