# Generated by Django 4.2.8 on 2024-02-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authors", "0002_remove_person_author_entries_author_details_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="orcid",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
