# Generated by Django 5.1.3 on 2025-01-27 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_use_single_author_role'),
        ('publications', '0033_alter_publication_open_access_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relevant_authors', to='publications.publication'),
        ),
    ]
