# Generated by Django 4.2.8 on 2024-02-05 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("institutions", "0001_initial"),
        ("authors", "0003_alter_person_orcid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="affiliation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="affiliated_authors",
                to="institutions.institution",
            ),
        ),
    ]
