# Generated by Django 4.2.8 on 2024-02-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authors", "0004_alter_author_affiliation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="email",
        ),
        migrations.RemoveField(
            model_name="person",
            name="name",
        ),
        migrations.AddField(
            model_name="author",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="author",
            name="name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
