# Generated by Django 4.2.8 on 2024-02-26 16:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authors", "0006_rename_details_author_identifier"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Person",
            new_name="PersonId",
        ),
    ]
