# Generated by Django 4.2.8 on 2024-04-26 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("journals", "0001_initial"),
        ("authors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "open_access_type",
                    models.CharField(
                        choices=[
                            ("Gold", "Gold"),
                            ("Diamond", "Diamond"),
                            ("Hybrid", "Hybrid"),
                            ("Unknown", "Unknown"),
                            ("Closed", "Closed"),
                        ],
                        default="Closed",
                    ),
                ),
                (
                    "license",
                    models.CharField(
                        choices=[
                            ("CC_BY", "CC-BY"),
                            ("CC_BY_SA", "CC-BY-SA"),
                            ("CC_BY_NC", "CC-BY-NC"),
                            ("CC_BY_NC_SA", "CC-BY-NC-SA"),
                            ("CC_BY_NC_ND", "CC-BY-NC-ND"),
                            ("CC_BY_ND", "CC-BY-ND"),
                            ("CC0", "CC0"),
                            ("Unknown", "Unknown"),
                            ("Proprietary", "Proprietary"),
                            ("None_", "None"),
                        ],
                        default="Unknown",
                    ),
                ),
                (
                    "publication_state",
                    models.CharField(
                        choices=[
                            ("Published", "Published"),
                            ("Unknown", "Unknown"),
                            ("Submitted", "Submitted"),
                            ("Accepted", "Accepted"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Unknown",
                        max_length=255,
                    ),
                ),
                ("publication_date", models.DateField(null=True)),
                ("author_list", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publications",
                        to="journals.journal",
                    ),
                ),
                (
                    "submitting_author",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_publication",
                        to="authors.author",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value", models.TextField()),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="publications.publication",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="publications.linktype"
                    ),
                ),
            ],
        ),
    ]
