# Generated by Django 4.2.8 on 2024-01-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="publication_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="publication_state",
            field=models.CharField(
                choices=[
                    ("published", "Published"),
                    ("accepted", "Accepted"),
                    ("submitted", "Submitted"),
                    ("rejected", "Rejected"),
                ],
                default="submitted",
                max_length=255,
            ),
        ),
    ]
