# Generated by Django 4.2.8 on 2024-06-10 12:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0002_rename_publication_state_publication_online_publication_state"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publication",
            old_name="publication_date",
            new_name="online_publication_date",
        ),
    ]
