# Generated by Django 4.2.8 on 2024-01-30 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authors", "0002_remove_person_author_entries_author_details_and_more"),
        ("publications", "0002_publication_publication_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="submitting_author",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submitted_publication",
                to="authors.author",
            ),
        ),
    ]
