# Generated by Django 4.2.8 on 2024-02-27 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0003_publication_submitting_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="publications",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links",
                to="publications.publication",
            ),
        ),
    ]
