# Generated by Django 4.2.8 on 2024-06-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0003_rename_publication_date_publication_online_publication_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="print_publication_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="print_publication_state",
            field=models.CharField(
                choices=[
                    ("Published", "Published"),
                    ("Unknown", "Unknown"),
                    ("Submitted", "Submitted"),
                    ("Accepted", "Accepted"),
                    ("Rejected", "Rejected"),
                ],
                default="Unknown",
                max_length=255,
            ),
        ),
    ]
