# Generated by Django 4.2.8 on 2024-04-05 11:04

import coda.apps.publications.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0006_alter_link_publication"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="open_access_type",
            field=models.CharField(
                choices=[
                    ("GOLD", "gold"),
                    ("DIAMOND", "diamond"),
                    ("HYBRID", "hybrid"),
                    ("CLOSED", "closed"),
                ],
                default=coda.apps.publications.models.OpenAccessType["CLOSED"],
            ),
        ),
    ]
