# Generated by Django 4.2.8 on 2024-06-12 12:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0006_publication_publication_type_vocabulary_version"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publication",
            name="print_publication_state",
        ),
    ]
