# Generated by Django 4.2.8 on 2024-04-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0007_publication_open_access_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="open_access_type",
            field=models.CharField(
                choices=[
                    ("GOLD", "Gold"),
                    ("DIAMOND", "Diamond"),
                    ("HYBRID", "Hybrid"),
                    ("CLOSED", "Closed"),
                ],
                default="CLOSED",
            ),
        ),
    ]
