# Generated by Django 4.2.8 on 2024-04-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0008_alter_publication_open_access_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="license",
            field=models.CharField(
                choices=[
                    ("CC_BY", "CC-BY"),
                    ("CC_BY_SA", "CC-BY-SA"),
                    ("CC_BY_NC", "CC-BY-NC"),
                    ("CC_BY_NC_SA", "CC-BY-NC-SA"),
                    ("CC_BY_NC_ND", "CC-BY-NC-ND"),
                    ("CC_BY_ND", "CC-BY-ND"),
                    ("CC0", "CC0"),
                    ("PROPRIETARY", "Proprietary"),
                    ("NONE", "None"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
            ),
        ),
    ]
