# Generated by Django 4.2.8 on 2024-06-26 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0008_rename_online_publication_state_publication_publication_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="subject_area",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="publications_of_subject",
                to="publications.concept",
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="publication_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="publications_with_type",
                to="publications.concept",
            ),
        ),
    ]
