# Generated by Django 5.0.7 on 2024-10-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_contract_journals"),
        ("publications", "0009_publication_subject_area_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="contracts",
            field=models.ManyToManyField(related_name="publications", to="contracts.contract"),
        ),
    ]
