# Generated by Django 4.2.8 on 2024-04-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0009_publication_license"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="publication_state",
            field=models.CharField(
                choices=[
                    ("published", "Published"),
                    ("accepted", "Accepted"),
                    ("submitted", "Submitted"),
                    ("rejected", "Rejected"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=255,
            ),
        ),
    ]
