# Generated by Django 5.0.7 on 2024-11-14 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0010_publication_contracts"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllowedPublicationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "concept",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="publications.concept",
                    ),
                ),
            ],
        ),
    ]
