# Generated by Django 4.2.8 on 2024-04-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0010_alter_publication_publication_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="author_list",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
