# Generated by Django 5.0.7 on 2024-11-14 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0011_allowedpublicationtype"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AllowedPublicationType",
            new_name="ForbiddenPublicationType",
        ),
    ]
