# Generated by Django 5.0.7 on 2024-11-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0012_rename_allowedpublicationtype_forbiddenpublicationtype"),
    ]

    operations = [
        migrations.AddField(
            model_name="concept",
            name="is_allowed",
            field=models.BooleanField(default=True),
        ),
    ]
