# Generated by Django 5.0.7 on 2024-11-15 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0013_concept_is_allowed"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ForbiddenPublicationType",
        ),
    ]
