# Generated by Django 5.0.7 on 2024-11-20 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0014_delete_forbiddenpublicationtype"),
    ]

    operations = [
        migrations.AddField(
            model_name="vocabulary",
            name="base_vocabulary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="publications.vocabulary",
            ),
        ),
        migrations.AddField(
            model_name="vocabulary",
            name="is_limited",
            field=models.BooleanField(default=False),
        ),
    ]
