# Generated by Django 5.0.7 on 2024-11-20 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0015_vocabulary_base_vocabulary_vocabulary_is_limited"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="concept",
            name="is_allowed",
        ),
    ]
