# Generated by Django 5.1.3 on 2024-11-25 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0016_remove_concept_is_allowed"),
    ]

    operations = [
        migrations.AddField(
            model_name="concept",
            name="base_vocabulary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="publications.vocabulary",
            ),
        ),
    ]
