# Generated by Django 5.1.3 on 2024-11-26 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0017_concept_base_vocabulary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concept',
            name='base_vocabulary',
        ),
    ]
