# Generated by Django 5.1.3 on 2024-11-28 16:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0018_remove_concept_base_vocabulary'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='entity_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
