# Generated by Django 5.1.3 on 2024-11-29 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0019_concept_entity_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publication",
            name="publication_type",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="subject_area",
        ),
    ]
