# Generated by Django 5.1.3 on 2024-11-29 11:32

import coda.apps.publications.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0020_remove_publication_publication_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicationAttachedConcept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("entity_id", models.UUIDField(default=uuid.uuid4)),
                (
                    "vocabulary",
                    models.ForeignKey(
                        default=coda.apps.publications.models.Vocabulary.empty,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="publications.vocabulary",
                    ),
                ),
            ],
        ),
    ]
