# Generated by Django 5.1.3 on 2024-11-29 13:04

import coda.apps.publications.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0021_publicationattachedconcept"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="publication_type",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="publications.publicationattachedconcept",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="subject_area",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="publications.publicationattachedconcept",
                null=True,
            ),
        ),
    ]
