# Generated by Django 5.1.3 on 2024-11-29 13:05

from django.db import migrations
from coda.domain.vocabulary import UnknownConcept


def generate_defaults(apps, schema_editor):
    Vocabulary = apps.get_model("publications", "Vocabulary")
    Vocabulary.objects.get_or_create(name="empty vocabulary", pk=UnknownConcept.vocabulary)
    Publication = apps.get_model("publications", "Publication")
    PublicationAttachedConcept = apps.get_model("publications", "PublicationAttachedConcept")

    for publication in Publication.objects.all():
        publication.publication_type = PublicationAttachedConcept.objects.create(
            entity_id=UnknownConcept.id, vocabulary_id=UnknownConcept.vocabulary
        )
        publication.subject_area = PublicationAttachedConcept.objects.create(
            entity_id=UnknownConcept.id, vocabulary_id=UnknownConcept.vocabulary
        )
        publication.save(update_fields=["publication_type", "subject_area"])


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0022_publication_publication_type_and_more"),
    ]

    operations = [migrations.RunPython(generate_defaults, reverse_code=migrations.RunPython.noop)]
