# Generated by Django 5.1.3 on 2024-11-29 13:05

import django
from django.db import migrations, models

import coda


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0023_publication_type_subject_area_gen_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="publication_type",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="publications.publicationattachedconcept",
                null=False,
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="subject_area",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="publications.publicationattachedconcept",
                null=False,
            ),
        ),
    ]
