# Generated by Django 5.1.3 on 2024-11-29 13:43

import coda.apps.publications.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0024_publication_type_subject_area_not_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="publication_type",
            field=models.OneToOneField(
                default=coda.apps.publications.models.PublicationAttachedConcept.unknown,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="publications.publicationattachedconcept",
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="subject_area",
            field=models.OneToOneField(
                default=coda.apps.publications.models.PublicationAttachedConcept.unknown,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="publications.publicationattachedconcept",
            ),
        ),
    ]
