# Generated by Django 5.1.3 on 2024-11-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0025_alter_publication_publication_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicationattachedconcept",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
