# Generated by Django 5.1.3 on 2024-12-09 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0003_remove_journal_open_access_type"),
        ("publications", "0026_publicationattachedconcept_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="journal",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publications",
                to="journals.journal",
            ),
        ),
    ]
