# Generated by Django 5.1.3 on 2024-12-09 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0027_alter_publication_journal"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publication",
            old_name="journal",
            new_name="article_journal",
        ),
    ]
