# Generated by Django 5.1.3 on 2024-12-09 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0028_rename_journal_publication_article_journal"),
        ("publishers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="monograph_publisher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publications",
                to="publishers.publisher",
            ),
        ),
    ]
