# Generated by Django 5.1.3 on 2024-12-16 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_contract_journals"),
        ("publications", "0029_publication_monograph_publisher"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttachedContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("contract_year", models.IntegerField()),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contracts.contract"
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attached_contracts",
                        to="publications.publication",
                    ),
                ),
            ],
        ),
    ]
