# Generated by Django 5.1.3 on 2024-12-16 10:27

from django.db import migrations


def move_publication_contracts_to_attachedcontracts(apps, schema_editor):
    Publication = apps.get_model("publications", "Publication")
    AttachedContract = apps.get_model("publications", "AttachedContract")
    for publication in Publication.objects.all():
        for contract in publication.contracts.all():
            AttachedContract.objects.create(
                contract=contract,
                publication=publication,
                contract_year=contract.start_date.year,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0030_attachedcontract"),
    ]

    operations = [migrations.RunPython(move_publication_contracts_to_attachedcontracts)]
