# Generated by Django 5.1.3 on 2024-12-16 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0031_move_publication_contracts_to_attachedcontracts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publication",
            name="contracts",
        ),
    ]
