# Generated by Django 5.1.3 on 2025-01-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0032_remove_publication_contracts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="open_access_type",
            field=models.CharField(
                choices=[
                    ("Gold", "Gold"),
                    ("Diamond", "Diamond"),
                    ("Hybrid", "Hybrid"),
                    ("Opt_in", "Opt-in"),
                    ("Opt_out", "Opt-out"),
                    ("Unknown", "Unknown"),
                    ("Closed", "Closed"),
                ],
                default="Closed",
            ),
        ),
    ]
