# Generated by Django 5.1.3 on 2025-02-12 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0033_alter_publication_open_access_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publication",
            name="submitting_author",
        ),
    ]
