# Generated by Django 5.1.3 on 2025-02-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0034_remove_publication_submitting_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="author_list",
            field=models.TextField(blank=True, null=True),
        ),
    ]
