# Generated by Django 5.1.3 on 2025-02-25 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_position_contract_year'),
        ('publications', '0035_alter_publication_author_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='invoices.invoice')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='publications.publication')),
            ],
        ),
    ]
