# Generated by Django 5.1.3 on 2025-02-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0036_publicationpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationpayment',
            name='status',
            field=models.CharField(default='unpaid', max_length=20),
        ),
    ]
