# Generated by Django 5.1.3 on 2025-02-25 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0038_alter_publicationpayment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationpayment',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='publications.publication', unique=True),
        ),
    ]
