# Generated by Django 5.1.6 on 2025-04-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0040_alter_publicationpayment_publication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="title",
            field=models.TextField(),
        ),
    ]
