# Generated by Django 5.1.6 on 2025-04-02 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0041_alter_publication_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicationpayment",
            name="publication",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="payment",
                to="publications.publication",
            ),
        ),
    ]
