# Generated by Django 5.1.8 on 2025-04-29 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0013_invoice_external_invoice_id_and_more"),
        ("publications", "0042_alter_publicationpayment_publication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicationpayment",
            name="invoice",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="invoices.invoice"
            ),
        ),
        migrations.AlterField(
            model_name="publicationpayment",
            name="publication",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="publications.publication",
            ),
        ),
    ]
