# Generated by Django 5.1.8 on 2025-09-15 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0043_alter_publicationpayment_invoice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicationpayment",
            name="publication",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="publications.publication",
            ),
        ),
    ]
