# Generated by Django 5.1.8 on 2025-10-16 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0044_alter_publicationpayment_publication"),
    ]

    operations = [
        migrations.AddField(
            model_name="concept",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="publications.concept",
            ),
        ),
    ]
