# Generated by Django 5.1.8 on 2025-12-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0044_alter_publicationpayment_publication"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="external_costsplitting",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="True if cost splitting occurred, None/null if unknown (omitted in OpenCost)",
                null=True,
            ),
        ),
    ]
