# Generated by Django 5.1.8 on 2026-01-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0045_add_external_costsplitting"),
        ("fundingrequests", "0033_migrate_external_costsplitting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publication",
            name="external_costsplitting",
        ),
    ]
