# Generated by Django 5.1.8 on 2026-01-12 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0045_add_external_costsplitting"),
        ("publications", "0045_concept_parent"),
        ("publications", "0046_remove_publication_external_costsplitting"),
    ]

    operations = []
