# Generated by Django 6.0.8 on 2026-10-07 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0047_merge_20260112_0843"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attachedcontract",
            options={"ordering": ("id",)},
        ),
    ]
