# Generated by Django 5.1.6 on 2025-03-13 13:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("journals", "0003_remove_journal_open_access_type"),
        ("publishers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(default="Blocklist", max_length=255)),
                (
                    "recommend_review_after",
                    models.DurationField(default=datetime.timedelta(days=180)),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BlockedPublisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("confirmed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="publishers.publisher"
                    ),
                ),
                (
                    "blocklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blocklist.blocklist"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BlockedJournal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("reason", models.CharField(max_length=255)),
                ("confirmed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="journals.journal"
                    ),
                ),
                (
                    "blocklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blocklist.blocklist"
                    ),
                ),
            ],
        ),
    ]
