# Generated by Django 5.1.6 on 2025-03-13 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blocklist", "0001_initial"),
        ("journals", "0003_remove_journal_open_access_type"),
        ("publishers", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="blockedjournal",
            unique_together={("blocklist", "journal")},
        ),
        migrations.AlterUniqueTogether(
            name="blockedpublisher",
            unique_together={("blocklist", "publisher")},
        ),
    ]
