# Generated by Django 5.1.6 on 2025-03-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blocklist", "0002_alter_blockedjournal_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockedjournal",
            name="reason",
            field=models.CharField(
                choices=[("MIRROR", "Mirror"), ("PREDATORY", "Predatory")], max_length=255
            ),
        ),
    ]
