# Generated by Django 5.1.3 on 2025-03-07 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fundingrequests', '0024_ensure_fundingrequestreview_present'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_name', models.CharField(max_length=255)),
                ('check_parameters', models.JSONField(null=True)),
                ('result', models.CharField(max_length=255)),
                ('result_data', models.JSONField(null=True)),
                ('timestamp', models.DateTimeField()),
                ('fundingrequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundingrequests.fundingrequest')),
            ],
        ),
    ]
