# Generated by Django 5.1.3 on 2025-03-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkrun',
            name='check_parameters',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='checkrun',
            name='result_data',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
