# Generated by Django 5.1.3 on 2025-03-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_alter_checkrun_check_parameters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkrun',
            name='check_parameters',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='checkrun',
            name='result_data',
            field=models.JSONField(default=dict),
        ),
    ]
