# Generated by Django 5.1.6 on 2025-03-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklist", "0003_alter_checkrun_check_parameters_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkrun",
            name="message",
            field=models.TextField(blank=True),
        ),
    ]
