name: Build and Deploy Docs

on:
    push:
        branches:
            - main
            - develop
            - docs
        paths:
            - 'docs/**'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: "3.12"

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pdm
            python -m pdm install -G docs

        - name: Build documentation
          run: |
            python -m pdm run sphinx-build -b html docs/ build/

        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v4
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./build/
